# Generated by Django 5.2.10 on 2026-01-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_issuebook_student_delete_task_issuebook_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll_no',
        ),
        migrations.AddField(
            model_name='issuebook',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
