# Generated by Django 5.2.10 on 2026-08-23 04:55

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_student_roll_no_issuebook_return_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Classification code (e.g. 004, QA, 823)', max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author']},
        ),
        migrations.AlterModelOptions(
            name='issuebook',
            options={'ordering': ['-issue_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='book',
            name='available_copies',
            field=models.PositiveIntegerField(default=1, help_text='Available copies for circulation'),
        ),
        migrations.AddField(
            model_name='book',
            name='call_number',
            field=models.CharField(blank=True, help_text='Shelf call number (e.g. QA76.73 .P98)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='ISBN-10 or ISBN-13', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='book',
            name='shelf_location',
            field=models.CharField(blank=True, help_text='Stack / Shelf coordinate', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='renewal_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active Loan'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue')], default='ACTIVE', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='General Studies', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='max_borrow_limit',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='student',
            name='patron_id',
            field=models.CharField(blank=True, help_text='Institutional Card ID', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('UNDERGRADUATE', 'Undergraduate Student'), ('POSTGRADUATE', 'Postgraduate Student'), ('FACULTY', 'Faculty / Professor'), ('RESEARCHER', 'Research Fellow'), ('STAFF', 'University Staff')], default='UNDERGRADUATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Total physical copies in collection'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='myapp.book'),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='myapp.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='myapp.category'),
        ),
        migrations.CreateModel(
            name='FineLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Settlement'), ('PAID', 'Settled / Paid'), ('WAIVED', 'Waived / Excused')], default='PENDING', max_length=15)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='myapp.issuebook')),
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_fines', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='myapp.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
